stevens = read.csv('4-stevens.csv')
str(stevens)

library(caTools)
set.seed(3000)
spl = sample.split(stevens$Reverse, SplitRatio = 0.7)
Train = subset(stevens, spl == TRUE)
Test = subset(stevens, spl == FALSE)

install.packages('rpart')
library(rpart)
install.packages('rpart.plot')
library(rpart.plot)
StevensTree = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method = 'class', minbucket = 25)
prp(StevensTree)

PredictCART = predict(StevensTree, newdata = Test, type = 'class')
table(Test$Reverse, PredictCART)
(41+71)/(41+36+22+71)

library(ROCR)
PredictROC = predict(StevensTree, newdata = Test)
PredictROC
pred = prediction(PredictROC[,2], Test$Reverse)
perf = performance(pred, 'tpr', 'fpr')
plot(perf)
as.numeric(performance(pred, 'auc')@y.values)

install.packages('randomForest')
library(randomForest)
Train$Reverse = as.factor(Train$Reverse)
Test$Reverse = as.factor(Test$Reverse)
StevensForest = randomForest(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, nodesize = 25, ntree = 200)
PredictForest = predict(StevensForest, newdata = Test)
table(Test$Reverse, PredictForest)
(40+74)/(40+37+19+74)

install.packages('caret')
library(caret)
install.packages('e1071')
library(e1071)
numFolds = trainControl(method = 'cv', number = 10)
cpGrid = expand.grid(.cp = seq(.01, .5, .01))
train(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method = 'rpart', trControl = numFolds, tuneGrid = cpGrid)
StevensTreeCV = rpart(Reverse ~ Circuit + Issue + Petitioner + Respondent + LowerCourt + Unconst, data = Train, method = 'class', cp = .19)
PredictCV = predict(StevensTreeCV, newdata = Test, type = 'class')
table(Test$Reverse, PredictCV)
(59+64)/(59+18+29+64)
prp(StevensTreeCV)
